### ISSUE TITLE
Question regarding exemplar selection

### ISSUE THREAD

**Issue by EvelynChee** [rahafaljundiTME/Continual-Novelty-Detection#1]
Hi, thanks for sharing your work. I have a question regarding the details of your exemplar selection under the shared head setting. In the paper, you mentioned that you used fixed buffer for each class. May I know how are the exemplars chosen? Is it random selection?  

On the other hand, in your code shown below, seems that you are using fixed overall memory budget instead of fixed memory per class? Also, samples are randomly selected from the whole dataset of the current task instead of randomly selected from each class within the dataset. May I know if you are using a different implementation? If so, would it be possible for you to share the code? Thanks.

https://github.com/rahafaljundiTME/Continual-Novelty-Detection/blob/c6fec7c9c34d69da88b3324d42ac5d10d2a45ed6/Continual_learning/continual_learning_traintest.py#L75-L95

**Comment by rahafaljundiTME** [comment]
Hi, 
You are right, we use a fixed buffer size overall and when a new task arrives, the number of samples per task is reduced with random selection.   At the end of the training, it will be approximately the number mentioned per class.  I mentioned in the paper that we follow https://arxiv.org/pdf/1909.08383.pdf in the buffer selection.  Apologies for the confusion.

**Comment by EvelynChee** [comment]
Noted. Thanks for the clarification.
